### PR TITLE
Create 40#issue-562168553

### PR DESCRIPTION
**Pull request by bdilts**

### CODE REVIEW

**Comment by bdilts** [comment]
> _No description provided._

**Comment by LittleCindy7** [comment]
Can you write a Code for: On my Nana's Feather? But this time make sure it's programmed to tell the truth. I mean after all you wouldn't want to lie on little Nana's head would ya?

**Comment by LittleCindy7** [comment]
Better cover your tracks because you wouldn't want all your friends or family to know what a dark life you live on the Nut Oops I mean .Net

**Comment by deviljackal** [comment]
Curious question. How much of our mortgage payments did you invest in cryptocurrency back in 07-08? I

**Pull request closed without merging**
